### ISSUE TITLE
Option chain not working after 1.5 upgrade

### ISSUE THREAD

**Issue by rajekra** [gporter0205/schwab-api-client#15]
Getting below error while fetching option chain,
org.springframework.web.reactive.function.client.WebClientResponseException$BadGateway: 502 Bad Gateway from GET https://api.schwabapi.com/marketdata/v1/chains

**Comment by gporter0205** [comment]
is this still a problem?

**Comment by rajekra** [comment]
Still not working for the request:
OptionChainRequest(symbol=SPY, contractType=CALL, strikeCount=null, includeQuotes=null, strategy=null, interval=null, strike=null, range=null, fromDate=2024-09-16, toDate=2024-09-16, volatility=null, underlyingPrice=null, interestRate=null, daysToExpiration=null, month=null, optionType=null)

**Comment by rajekra** [comment]
![image](https://github.com/user-attachments/assets/8d9d0f90-1bd2-4fac-a350-79a532cdbcc2)

**Comment by rajekra** [comment]
String expirationDate = "2024-09-16";
    	OptionChainRequest optionChainRequestCall =  OptionChainRequest.builder()
    			.withSymbol(symbol)
    			.withContractType(ContractType.CALL)
    			.withFromDate(LocalDate.parse(expirationDate, DateTimeFormatter.ofPattern("yyyy-MM-dd")))
    			.withToDate(LocalDate.parse(expirationDate, DateTimeFormatter.ofPattern("yyyy-MM-dd"))).build();

    	System.out.println("optionChainRequest:" +optionChainRequestCall.toString());

		return schwabMarketDataApiClient.fetchExpirationChainToMono(symbol);

**Comment by gporter0205** [comment]
It doesn't work if you call the chains end point directly on the Schwab developer portal either so it's a problem with either their API or their documentation. You may want to contact Schwab support.
