### ISSUE TITLE
Option chain not working with from and to date with time:  Actual format is  yyyy-MM-dd

### ISSUE THREAD

**Issue by rajekra** [gporter0205/schwab-api-client#16]
Option chain not working with from and to date with time:  Actual format is  yyyy-MM-dd and need to replace this with LocalDate instead of LocalDateTime

**Comment by gporter0205** [comment]
I'm taking a look.  I haven't used option chain in my app so this endpoint is probably in need of some attention.

**Comment by gporter0205** [comment]
Are you able to use the /chain endpoint in swagger on their dev portal?  I can't even get that to work.

**Comment by rajekra** [comment]
Thru schwab developer portal, i am able to request.
![image](https://github.com/user-attachments/assets/a0458e61-c620-4f2d-80f1-293089fcd321)

From date format from developer site:
![image](https://github.com/user-attachments/assets/fc5bb40a-9dcd-43e5-a2d0-f67b117ad95b)

**Comment by gporter0205** [comment]
What happens when you populate the fromDate and toDate using the yyyy-MM-dd pattern that they recommend?  I'm getting a 400 - Bad Request response back.

**Comment by gporter0205** [comment]
![image](https://github.com/user-attachments/assets/b14773d6-099e-4c35-9b06-55ab6d9387b8)

**Comment by gporter0205** [comment]
Change to the date formats has been made.  I still can't get the dates to work even formatted correctly directly through Schwab's swagger site.
