### ISSUE TITLE
schwab-api-client test case failures

### ISSUE THREAD

**Issue by higgsja** [gporter0205/schwab-api-client#17]
I really appreciate you taking up the gauntlet on this!

When I build the client I get the following error on every test case:
com.pangility.schwab.api.client.unittest.SchwabMarketDataApiTest.optionQuoteNotFoundTest -- Time elapsed: 0.828 s <<< ERROR!
java.time.format.DateTimeParseException: Text '${schwab-api.oauth2.refreshExpiration}' could not be parsed at index 0

I do not see where this variable is set.

**Comment by gporter0205** [comment]
To run the tests, you'll need to create a file under the test resources folder of the project called application-unittest.yml with the following entries:
`schwab-api:
  oauth2:
    userId: <YOUR-SCHWAB-USERID>
    refreshToken: <REFRESH-TOKEN-VALIDATED-AGAINST-YOUR-ACCOUNT>
    refreshExpiration: <EXPIRATION-OF-THE-REFRESH-TOKEN-yyyy-mm-ddThh:mm:ss>
    clientId: <YOUR-SCHWAB-CLIENT-ID>
    clientSecret: <YOUR-SCWAB-CLIENT-SECRET>
    redirect-uri: <YOUR-SCHWAB-REDIRECT-URI>`
