### ISSUE TITLE
refreshToken refreshExpiration help

### ISSUE THREAD

**Issue by peterboivin** [gporter0205/schwab-api-client#2]
I am a little foggy on refreshToken and refreshExpiration.  Are these generated values? Do I get them on the Schwab dev portal?

**Comment by gporter0205** [comment]
check out the wiki for some step by step instructions on how to use this api client.  I just put them together so let me know if they aren't clear or need more detail.  https://github.com/gporter0205/schwab-api-client/wiki

**Comment by peterboivin** [comment]
Great. Thank you.  I am glad I am not alone in finding it confusing.
