### ISSUE TITLE
Cannot deserialize value of type FLATTEN

### ISSUE THREAD

**Issue by diya1991** [gporter0205/schwab-api-client#20]
2024-09-11T16:58:24.020-07:00  INFO 7482 --- [ctor-http-nio-3] .a.c.a.SchwabAccountsAndTradingApiClient : Fetch Account [3099AC] with positions
Error in processing orders or placing a new order: JSON decoding error: Cannot deserialize value of type `com.pangility.schwab.api.client.accountsandtrading.model.order.OrderStrategyType` from String "FLATTEN": not one of the values accepted for Enum class: [SINGLE, OCO, TRIGGER]

**Comment by diya1991** [comment]
can we prioritize it, this looks like a minor change adding new Enum FLATTEN

**Comment by gporter0205** [comment]
It is a minor change that I've made.  I'll be promoting it today if all goes well.
