### ISSUE TITLE
Unable to retrieve token: 

### ISSUE THREAD

**Issue by rajekra** [gporter0205/schwab-api-client#5]
Tried latest sample and getting below error. Which one have to use as clinet id?
Unable to retrieve token: { "error" : "unsupported_token_type", "error_description" : "400BadRequest : \"{ \"error_description\" : \"Exceptionwhileauthenticatingrefreshtoken[tokenDigest=s9AGpDq1NyE1QhirVJ4uyUTgB0PUcfbRbvGfyg0356k=, Exception=Failedrefreshtokenauthentication[tokenDigest=s9AGpDq1NyE1QhirVJ4uyUTgB0PUcfbRbvGfyg0356k=]]\", \"error\" : \"refresh_token_authentication_error\" }\"" }

**Comment by gporter0205** [comment]
Hi check out the wiki. I put some step by step instructions there that will hopefully help you get it working.

**Comment by rajekra** [comment]
Working as expected
