### ISSUE TITLE
Place order rendering assetType 2 times which leads to 500 error from server

### ISSUE THREAD

**Issue by rajekra** [gporter0205/schwab-api-client#8]
{
  "session" : "NORMAL",
  "duration" : "DAY",
  "orderType" : "LIMIT",
  "price" : 64.99,
  "orderLegCollection" : [ {
    "instruction" : "BUY",
    "quantity" : 1,
    "instrument" : {
      "assetType" : "EQUITY",
      "assetType" : "EQUITY",
      "symbol" : "TQQQ"
    }
  } ],
  "orderStrategyType" : "TRIGGER",
  "childOrderStrategies" : [ {
    "session" : "NORMAL",
    "duration" : "DAY",
    "orderType" : "LIMIT",
    "price" : 65.30,
    "orderLegCollection" : [ {
      "instruction" : "SELL",
      "quantity" : 1,
      "instrument" : {
        "assetType" : "EQUITY",
        "assetType" : "EQUITY",
        "symbol" : "TQQQ"
      }
    } ],
    "orderStrategyType" : "SINGLE"
  } ]
}

**Comment by gporter0205** [comment]
Hi.  I haven't been able to test the order methods yet so I'm not surprised there are bugs.  They would be a lot easier to test if Schwab had a test environment.  I'll take a look.  If you are comfortable, I'm fine if you create a branch, fix it and submit a pull request as well.  Let me know.

**Comment by gporter0205** [comment]
I found the problem.  I'm testing it and will be releasing an update hopefully tomorrow.

**Comment by rajekra** [comment]
THANKS @gporter0205 . this is Very quick turnaround.

**Comment by gporter0205** [comment]
Ok, I tested the placeOrder method with both equity and option orders.  v0.1.3 is published to Maven Central with the fix and a lot of other stuff.  Check out the Versions page on the wiki for more info.

**Comment by rajekra** [comment]
Thanks. Let me execute during live market tomorrow and update if any issues.
